#!/bin/bash

ARCH="${1}"
OUTPUT=output
PACKAGE="${2}"

if [ "${ARCH}" == "amd64" ]; then
  DEBIAN_RELEASE=stretch
else
  DEBIAN_RELEASE=buster
fi

if [ "${PACKAGE}" == "" ] || [ "${PACKAGE}" == "peach-base" ]; then
  debian-package-builder --docker --target base --arch "${ARCH}" --input packages/peach-base --output "${OUTPUT}" --debian-release ${DEBIAN_RELEASE}
fi

if [ "${PACKAGE}" == "" ] || [ "${PACKAGE}" == "peach-ssb-server" ]; then
  debian-package-builder --docker --target nodejs --arch "${ARCH}" --input packages/peach-ssb-server --output "${OUTPUT}" --debian-release ${DEBIAN_RELEASE}
fi

if [ "${PACKAGE}" == "" ] || [ "${PACKAGE}" == "peach-dyndns-host" ]; then
  debian-package-builder --docker --target python --arch "${ARCH}" --input packages/peach-dyndns-host --output "${OUTPUT}" --debian-release ${DEBIAN_RELEASE}
fi

if [ "${PACKAGE}" == "" ] || [ "${PACKAGE}" == "peach-dyndns-guest" ]; then
  debian-package-builder --docker --target base --arch "${ARCH}" --input packages/peach-dyndns-guest --output "${OUTPUT}" --debian-release ${DEBIAN_RELEASE}
fi
