archive = "buster"
version = "10"
origin = "peachcloud"
label = "PeachCloud"
email = "dev@peachcloud.org"
architectures = [
  "amd64",
  "i386",
  "arm64",
  "armhf"
]

# https://github.com/system76/cuda/blob/master/suites/bionic.toml

[[source]]
name = "peach-base"
build_on = "changelog"

  [source.location]
  git = "git://github.com/peachcloud/peach-base"

[[source]]
name = "peach-upnp"
build_on = "changelog"
assets = [
   { src = "cargo_makefile", dst = "Makefile" }
]

  [source.location]
  git = "git://github.com/peachcloud/peach-upnp"
